### ISSUE TITLE
请教一些问题

### ISSUE THREAD

**Issue by maicWorkGithub** [jswh/synology_video_station_douban_plugin#1]
1. 这个是替换还是增加源？
2. 我想用js重写一遍，因为不懂php。但是我不知道逻辑（看不懂php代码……，能不能大概说一下？谢谢
3. 这个有文档吗？

**Comment by jswh** [comment]
1. 整体上是替换了 video station 的程序代码，把中文的信息搜索走到了豆瓣。看 install.sh 可以明白替换了哪些。
2. 如果只是看豆瓣的爬虫只要看douban.php文件就行了，其余很多都是video station的固定函数接口。基本的思路是从wap版的豆瓣页面获取搜索结果，然后才web版的详情页获取具体内容。分析页面没有走复杂的工具，都是正则和字符串处理。
3. 文档目前没有。

**Comment by maicWorkGithub** [comment]
你们都是用PHP写的，是群晖要求PHP么，如果不要求，我想用node写。

`整体上替换了video station的代码`的意思是，video station的代码就是这样写的，只是地址规则不一样？如果是这样，能不能把video station代码的路径说一下？

谢谢！！

**Comment by jswh** [comment]
对的，video station 原生的代码就是PHP，这个只是把原来的代码修改了。
没有具体研究果video station的完整系统，所以不确定能不能用node来写。

**Comment by maicWorkGithub** [comment]
我回去看了，的确是php写的，不能使用node，或者最起码使用PHP包一层，谢谢了。

另外我发现的问题：
1. 影片简介有标签`<br/>`出现
2. 图片源是豆瓣了的，但是为啥还经常会出现下载失败的情况？
3. 现在是全是豆瓣的还是豆瓣找不到的时候去其他网站接着找？（代码我没看懂……我就是想增加这个功能，还想增加字幕下载源，国外的中文字幕太少了

---
最后还有一个请求，能不能添加一个功能，读取电影的时候，如果本文件内有跟电影同名的配置文件（电影元信息）、同名的thumb.jpg、同名的background.jpg的时候直接使用？或者这样：
```
// 每个电影一个文件夹
|__卧虎藏龙
    |__ 卧虎藏龙.1080P.mkv
    |__ thumb.jpg
    |__ background.jpg
    |__ info.yaml/info.json
```

**Comment by jswh** [comment]
目前没有添加新功能的计划的😊
