### ISSUE TITLE
太需要了。给你点个赞

### ISSUE THREAD

**Issue by yang9w** [jswh/synology_video_station_douban_plugin#16]
隔壁的那个不支持电视剧频道。唉。你的这个不错。

**Comment by yang9w** [comment]
1. ssh登录群晖系统
2. 执行`wget https://dor.ins.cx/install.sh`
3. 执行`sudo bash install.sh uninstall`（第一次安装可以跳过这个步骤）
4. 执行`sudo bash install.sh install`
我的群晖上不了GitHub。只能搬运到自己的服务器再安装了。实测可以用。很好

**Comment by jswh** [comment]
感谢

**Comment by 245432007** [comment]
点赞+1
