### ISSUE TITLE
uninstall的脚本路径有误

### ISSUE THREAD

**Issue by lowlandsheperd** [jswh/synology_video_station_douban_plugin#26]
install:
`sed "s/CF_WORKER_URL/$2/g" $vPlugins/syno_file_assets/douban.tmp.php > $vPlugins/**syno_file_assets**/douban.php`

uninstall:
`rm $vPlugins/**syno_themoviedb**/douban.php`

**Comment by jswh** [comment]
fix.
谢谢~
