### ISSUE TITLE
缺少分号

### ISSUE THREAD

**Issue by lowlandsheperd** [jswh/synology_video_station_douban_plugin#27]
https://github.com/jswh/synology_video_station_douban_plugin/blob/fae98bf423585ec7950325c3a5b084e5b6460a00/syno_file_assets/douban.tmp.php#L4

**Comment by lowlandsheperd** [comment]
是不是现在的master版本是一个开发版本？
我的机器还会报一个warning
PHP Startup: Unable to load dynamic library '/lib/php/modules/json.so'

**Comment by jswh** [comment]
fix
后面的问题是php没有json扩展

**Comment by lowlandsheperd** [comment]
php json扩展在群晖里默认是没有的，是不是因为装了某个其他的套件安装了？这个得提示一下，否则会一直返回空值。
