### ISSUE TITLE
摘要空白和电视单集数据问题

### ISSUE THREAD

**Issue by ghost** [jswh/synology_video_station_douban_plugin#3]
1.影片的摘要字段会出现大片的空格和`<br />`
2.电视剧的集标题偶尔会出现错乱的情况，比如标题是集标题是英文的、繁体的甚至是其他剧集的。即便手动搜索刮削也不能改变这样的情况，出现这个问题的剧集有如下几步
三国.Three Kingdoms(2010)
芈月传.Legend of Miyue(2015)
中国通史.General History of China(2013)

下面这几部片子抓不到，其他的都可以。
金瓶双艳https://movie.douban.com/subject/3801357/
河西走廊https://movie.douban.com/subject/24736278/
神秘的西夏https://movie.douban.com/subject/26351794/

**Comment by jswh** [comment]
1.这个我近期处理一下，如果可以像2一样提供一下示例就好啦
2.电视剧的单集数据抓取还是延用之前的。如果之后改动这一块了再看看能不能修复。

**Comment by jswh** [comment]
请更新后再尝试看看
