### ISSUE TITLE
请问为什么刮削出来的电影大多都是英文的？

### ISSUE THREAD

**Issue by QiuSimons** [jswh/synology_video_station_douban_plugin#4]
请问为什么刮削出来的电影大多都是英文的标题和封面，是有什么设置上的问题么

**Comment by jswh** [comment]
是不是你系统是英文的？

**Comment by QiuSimons** [comment]
中文系统

**Comment by jswh** [comment]
出来的数据是英文，应该是走到国外的数据源抓取了。上次的改动中已经改成默认从豆瓣获取数据了，但是系统语言如果是英文还是会走到国外的数据源。对于这个语言判定我目前也还是不是特别明白是怎么回事，您可以先手动处理一下英文的内容，并关注一下后面的更新。

**Comment by SimonsQiu** [comment]
> 出来的数据是英文，应该是走到国外的数据源抓取了。上次的改动中已经改成默认从豆瓣获取数据了，但是系统语言如果是英文还是会走到国外的数据源。对于这个语言判定我目前也还是不是特别明白是怎么回事，您可以先手动处理一下英文的内容，并关注一下后面的更新。

好的，我到时候更新了再试试~，谢谢您的插件

**Comment by jswh** [comment]
已经改了，您再试试
