### ISSUE TITLE
安装提示错误

### ISSUE THREAD

**Issue by leverule** [jswh/synology_video_station_douban_plugin#8]
一开始使用
`wget https://raw.githubusercontent.com/jswh/synology_video_station_douban_plugin/master/install.sh`
提示连接错误，看了路径又改为
`wget https://github.com/jswh/synology_video_station_douban_plugin/blob/master/install.sh`
成功下载，但是安装错误：
```
root@Hyperspace:~# sudo bash install.sh install
install.sh: line 7: syntax error near unexpected token `newline'
install.sh: line 7: `<!DOCTYPE html>'
```
请问可以更新下吗，谢谢您
（目前使用918+6.2.2up4系统，套件版本最新）

**Comment by jswh** [comment]
install.sh: line 7: `<!DOCTYPE html>'

这个明显下载的文件里面不是shell，是html文件，
还是需要 
`wget https://raw.githubusercontent.com/jswh/synology_video_station_douban_plugin/master/install.sh`
才是下载原始文件，连接失败应该是你被墙了

**Comment by jswh** [comment]
如果 wget 还是失败，建议在电脑上下载之后上传到nas，这个 issue 我先close了
