### ISSUE TITLE
出现“文件大于4MB”

### ISSUE THREAD

**Issue by ghost** [jswh/synology_video_station_douban_plugin#9]
很好用。不过有点小问题，我讲一下我遇到的。
有时候电影有些海报刮不出来，提示“文件大于4MB”， 我看了下，应该是海报图片大于4MB。例如《绿皮书》这电影，博主插件调用的海报地址是“https://api.9hut.cn/pic.php?url=
https://img3.doubanio.com/view/photo/raw/public/p2549177902.jpg”， 这张海报原图是大于4MB（原图是5.96MB），博主可以改成调用小于4MB的么，或者例子中，把“raw” 改成“l”，即https://img3.doubanio.com/view/photo/l/public/p2549177902.jpg 就行。
豆瓣图片 应该有 raw/l/m/s，这几种吧

**Comment by jswh** [comment]
已经改了
